spring:
  application:
    name: iam-policy-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client-id: iam-policy-service
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      linger-ms: 5
      retries: 3
      properties:
        spring.json.add.type.headers: true
        spring.json.write-dates-as-timestamps: false
        compression.type: lz4
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
audit:
  kafka:
    enabled: true
    login-topic: iam.audit.login
    policy-topic: iam.audit.policy
    client-id: iam-policy-service
management:
  metrics:
    tags:
      application: iam-policy-service
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
