server:
  port: 8081

spring:
  application:
    name: iam-account-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloudgate_iam?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: cloudgate
    password: cloudgate-pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

auth:
  resource:
    issuer: http://localhost:8080

management:
  metrics:
    tags:
      application: iam-account-service
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
